//
// Generated file, do not edit! Created by opp_msgtool 6.0 from apps/shore/messages/NackPacket.msg.
//

#ifndef __NACKPACKET_M_H
#define __NACKPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class NackPacket;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>apps/shore/messages/NackPacket.msg:8</tt> by opp_msgtool.
 * <pre>
 * class NackPacket extends inet::FieldsChunk
 * {
 *     chunkLength = inet::B(1);
 * 
 *     int sequenceNumber;
 * 
 *     // for simplicity
 *     string streamName;
 * }
 * </pre>
 */
class NackPacket : public ::inet::FieldsChunk
{
  protected:
    int sequenceNumber = 0;
    omnetpp::opp_string streamName;

  private:
    void copy(const NackPacket& other);

  protected:
    bool operator==(const NackPacket&) = delete;

  public:
    NackPacket();
    NackPacket(const NackPacket& other);
    virtual ~NackPacket();
    NackPacket& operator=(const NackPacket& other);
    virtual NackPacket *dup() const override {return new NackPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual const char * getStreamName() const;
    virtual void setStreamName(const char * streamName);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NackPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NackPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline NackPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<NackPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __NACKPACKET_M_H

