//
// Generated file, do not edit! Created by opp_msgtool 6.0 from apps/shore/messages//TransportFeedbackChunk.msg.
//

#ifndef __TRANSPORTFEEDBACKCHUNK_M_H
#define __TRANSPORTFEEDBACKCHUNK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TransportFeedbackChunk;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>apps/shore/messages//TransportFeedbackChunk.msg:8</tt> by opp_msgtool.
 * <pre>
 * class TransportFeedbackChunk extends inet::FieldsChunk
 * {
 *     chunkLength = inet::B(3);
 * 
 *     string streamName; // auxilary
 *     int sequenceNumber;
 *     simtime_t recvDelta;
 * }
 * </pre>
 */
class TransportFeedbackChunk : public ::inet::FieldsChunk
{
  protected:
    omnetpp::opp_string streamName;
    int sequenceNumber = 0;
    omnetpp::simtime_t recvDelta = SIMTIME_ZERO;

  private:
    void copy(const TransportFeedbackChunk& other);

  protected:
    bool operator==(const TransportFeedbackChunk&) = delete;

  public:
    TransportFeedbackChunk();
    TransportFeedbackChunk(const TransportFeedbackChunk& other);
    virtual ~TransportFeedbackChunk();
    TransportFeedbackChunk& operator=(const TransportFeedbackChunk& other);
    virtual TransportFeedbackChunk *dup() const override {return new TransportFeedbackChunk(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getStreamName() const;
    virtual void setStreamName(const char * streamName);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual omnetpp::simtime_t getRecvDelta() const;
    virtual void setRecvDelta(omnetpp::simtime_t recvDelta);


  public:
    virtual std::string str() const override;
    virtual void dump(std::ostream& os) const;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransportFeedbackChunk& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransportFeedbackChunk& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TransportFeedbackChunk *fromAnyPtr(any_ptr ptr) { return check_and_cast<TransportFeedbackChunk*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TRANSPORTFEEDBACKCHUNK_M_H

